- name: Test pull playbook
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
  - include: tasks/packages.yml

- name: My play
  import_playbook: playbook.yml
