- name: Test playbook
  hosts: localhost
  tasks:
    - name: Test logname
      ansible.builtin.shell: logname
      register: logname_output
      args:
        executable: /bin/bash
    - ansible.builtin.debug:
        var: logname_output
